-- liquibase formatted sql

-- changeset developer:1
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'tm_balances';
CREATE TABLE tm_balances
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by INTEGER,
    user_id    INTEGER                                   NOT NULL,
    balance    DECIMAL(10, 2)              DEFAULT 0     NOT NULL,
    is_active  BOOLEAN                     DEFAULT TRUE  NOT NULL,
    pin        VARCHAR(255)                              NOT NULL,
    CONSTRAINT pk_tm_balances PRIMARY KEY (id)
);

CREATE TABLE td_balance_histories
(
    id           UUID                                      NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    created_by   INTEGER,
    updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by   INTEGER,
    balance_id   INTEGER                                   NOT NULL,
    type         VARCHAR(255)                              NOT NULL,
    amount       DECIMAL(10, 2)              DEFAULT 0     NOT NULL,
    status       VARCHAR(255)                              NOT NULL,
    token        VARCHAR(255),
    redirect_url VARCHAR(255),
    CONSTRAINT pk_td_balance_histories PRIMARY KEY (id)
);

ALTER TABLE td_balance_histories
    ADD CONSTRAINT FK_TD_BALANCE_HISTORIES_ON_BALANCE FOREIGN KEY (balance_id) REFERENCES tm_balances (id);

-- rollback DROP TABLE td_balance_histories CASCADE;
-- rollback DROP TABLE tm_balances CASCADE;
