CREATE TABLE tm_balances
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by INTEGER,
    user_id    INTEGER                                   NOT NULL,
    balance    DECIMAL(10, 2)              DEFAULT 0     NOT NULL,
    is_active  BOOLEAN                     DEFAULT TRUE  NOT NULL,
    pin        VARCHAR(255)                              NOT NULL,
    CONSTRAINT pk_tm_balances PRIMARY KEY (id)
);