ALTER TABLE td_balance_histories
    ADD COLUMN IF NOT EXISTS payment_type VARCHAR(50),
    ADD COLUMN IF NOT EXISTS bank VARCHAR(50),
    ADD COLUMN IF NOT EXISTS va_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bill_key VARCHAR(100),
    ADD COLUMN IF NOT EXISTS biller_code VARCHAR(100),
    ADD COLUMN IF NOT EXISTS qr_url TEXT,
    ADD COLUMN IF NOT EXISTS qr_string TEXT,
    ADD COLUMN IF NOT EXISTS deeplink_url TEXT,
    ADD COLUMN IF NOT EXISTS expiry_time VARCHAR(100);
